### PR TITLE
WIP: Slide uploads (continuation on benjaomings work)

### PR DESCRIPTION
**Pull request by valberg**
Just added the `slideshow-upload` from @benjaoming's repo to the bornhack-website repo so I can continue work on it.

Original PR is here: https://github.com/bornhack/bornhack-website/pull/155

### CODE REVIEW

**Comment by valberg** [comment]
Going to get this in when https://github.com/bornhack/bornhack-website/pull/184 is done and merged.

**Comment by tykling** [comment]
closing old PRs. Slide uploads will be to BMA in the future :+1:

**Comment by benjaoming** [comment]
What is BMA? :shrug:

**Comment by valberg** [comment]
@benjaoming BornHack Media Archive: https://github.com/bornhack/bma :)

**Comment by benjaoming** [comment]
oy, what the heck, that's a lot of code you've been writing there @tykling  :eyes:

**Pull request closed without merging**
